name: Deploy to Locaweb

on:
  push:
    branches:
      - master # Se a sua branch principal for 'master', mude aqui.

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependências e Build
        run: |
          npm install
          npm run build

      - name: FTP Deploy para Locaweb
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/ # O Vite gera o site pronto aqui dentro (mantenha a barra no final)
          server-dir: /public_html/ # Pasta raiz da sua hospedagem na Locaweb (mantenha a barra no final)